name: $(Build.BuildId)

# Triggers Pipeline only on Master
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - LICENSE

schedules:
- cron: "0 6 * * 1-5"
  displayName: Daily rollover at 05:00 UTC
  branches:
    include:
    - master
  always: "true"

# Disables triggering Pipeline run at creation of every Pull Request
pr: none

# Global variables for the pipeline
variables:
  vmImage: 'ubuntu-latest'
  k8s-service-connection: 'Kubernetes-Hellman'
  kubernetes-namespace: 'monitoring'
  run-update: 'true'

stages:
# Continuous Deployment steps
- stage: CD
  displayName: 'Continuous Deployment'

  jobs:
  - job: Validate
    displayName: 'Validate if new release is available'
    pool: 
      vmImage: $(vmImage)

    steps:
    # Script validates if a new docker container has been created or helm chart has been updated
    # If updated, a pipeline variable is set to allow the pipeline to run an update
    - task: Bash@3
      inputs:
        targetType: 'filePath'
        filePath: update-check.sh 

  - job: Helm
    displayName: 'Deploy to Kubernetes'
    pool: 
      vmImage: $(vmImage)
    dependsOn: Validate
    condition: and(succeeded('Validate'), eq(variables['run-update'], 'true')) 
  
    steps:
    # Install the Helm binary to the host machine
    - task: HelmInstaller@1
      displayName: 'Helm client installer'
      inputs: 
        helmVersionToInstall: latest

    # Initialize the Helm binary & upgrade tiller if version is lower than Helm
    - task: HelmDeploy@0
      displayName: 'Helm initialize'
      inputs:
        connectionType: Kubernetes Service Connection
        kubernetesServiceEndpoint: $(k8s-service-connection)
        command: init
        upgradetiller: true
        waitForExecution: true
        arguments: --client-only

    # Install helm chart, if already present, upgrade it
    - task: HelmDeploy@0
      displayName: 'Helm initialize stable repository'
      inputs:
        connectionType: Kubernetes Service Connection
        kubernetesServiceEndpoint: $(k8s-service-connection)
        command: 'repo'
        arguments: 'add stable https://kubernetes-charts.storage.googleapis.com/'


    # Install helm chart, if already present, upgrade it
    - task: HelmDeploy@0
      displayName: 'Helm chart Install / Upgrade'
      inputs:
        connectionType: Kubernetes Service Connection
        kubernetesServiceEndpoint: $(k8s-service-connection)
        chartName: 'stable/goldpinger'
        releaseName: 'goldpinger'
        command: 'upgrade'
        install: true 
        arguments: --namespace $(kubernetes-namespace) --set image.tag=$(image)
        waitForExecution: false
    
    # Add label to the release for prometheus scraping
    - task: Kubernetes@1
      displayName: kubectl apply
      inputs:
        connectionType: Kubernetes Service Connection
        kubernetesServiceEndpoint: $(k8s-service-connection)
        command: label
        arguments: services goldpinger scrape-service-metrics="true"
